services:
   web:
      build: docker/web
      hostname: web
      ports:
         - 8000:80
      volumes:
         - ./configs:/etc/apache2/sites-enabled
         - ./pages:/web

      networks:
         rede_test:
            aliases:
               - www.proba.lan
               - proba.lan

   cliente:
      build: docker/cliente
      hostname: cliente
      networks:
         - rede_test
      environment:
         - DISPLAY=${DISPLAY}
      volumes:
         - /tmp/.X11-unix:/tmp/.X11-unix

networks:
   rede_test:
