services:
   web:
      build: docker/web
      hostname: web
      ports:
         - 8000:80
      volumes:
         - ./configs:/etc/apache2/sites-enabled
         - ./pages/server1:/web/server1
         - ./pages/server2:/web/server2
         - ./pages/alias:/srv
         - ./certificados:/certificados

      networks:
         rede_test:
            aliases:
               - proba.lan
               - server1.lan
               - server2.lan
               - www.proba.lan
               - www.server1.lan
               - www.server2.lan

   cliente:
      build: docker/cliente
      hostname: cliente
      networks:
         rede_test:
           # ipv4_address: 172.21.0.3/16

      environment:
         - DISPLAY=${DISPLAY}
      volumes:
         - /tmp/.X11-unix:/tmp/.X11-unix
      entrypoint: "firefox"

networks:
   rede_test:

